language: java
jdk:
  - oraclejdk8
branches:
  except:
    - master
    - save
addons:
  apt:
    packages:
      - python2.7
before_script:
  - unset _JAVA_OPTIONS
script:
  - bash deploy.sh
deploy:
  provider: releases
  api_key:
    secure:
  file_glob: true
  file:
    - eufix-magisk-*.zip
  overwrite: true
  skip_cleanup: true
  on:
    repo: kooritea/mipay-extract
    tags: true
